//
// Copyright 2020 FoxyUtils ehf. All rights reserved.
//
// This is a commercial product and requires a license to operate.
// A trial license can be obtained at https://unidoc.io
//
// DO NOT EDIT: generated by unitwist Go source code obfuscator.
//
// Use of this source code is governed by the UniDoc End User License Agreement
// terms that can be accessed at https://unidoc.io/eula/

package license

import (
	"bytes"
	"compress/gzip"
	"crypto"
	"crypto/aes"
	"crypto/cipher"
	"crypto/hmac"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/sha512"
	"crypto/x509"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"github.com/unidoc/unipdf/v4/common"
	"io"
	"net"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"
)

var _edb = &sync.Mutex{}

func _cff() (string, error) {
	_dae := strings.TrimSpace(os.Getenv(UnidocLicenseDir))
	if _dae == "" {
		common.Log.Debug("$%s environment variable not found. Will use home directory to store license information.", UnidocLicenseDir)
		_abdc := _aefc()
		if len(_abdc) == 0 {
			return "", fmt.Errorf("required $%s environment variable or home directory not found", UnidocLicenseDir)
		}
		_dae = filepath.Join(_abdc, ".unidoc")
	}
	_ddce := os.MkdirAll(_dae, 0777)
	if _ddce != nil {
		return "", _ddce
	}
	return _dae, nil
}

const (
	licenseKeyHeader = "-----BEGIN UNIDOC LICENSE KEY-----"
	licenseKeyFooter = "-----END UNIDOC LICENSE KEY-----"
)

func TrackUse(useKey string) {
	if defaultLicenseKey == nil {
		return
	}
	if !defaultLicenseKey._eg || len(defaultLicenseKey._da) == 0 {
		return
	}
	if len(useKey) == 0 {
		return
	}
	_edb.Lock()
	defer _edb.Unlock()
	if _aagc == nil {
		_aagc = map[string]int{}
	}
	_aagc[useKey]++
}

var date20100101 = time.Date(2010, 1, 1, 0, 0, 0, 0, time.UTC)

func _fdc(_fdd string, _dbce []byte) (string, error) {
	_aeg, _ := pem.Decode([]byte(_fdd))
	if _aeg == nil {
		return "", fmt.Errorf("PrivKey failed")
	}
	_ge, err := x509.ParsePKCS1PrivateKey(_aeg.Bytes)
	if err != nil {
		return "", err
	}
	_gb := sha512.New()
	_gb.Write(_dbce)
	_bb := _gb.Sum(nil)
	_gbg, err := rsa.SignPKCS1v15(rand.Reader, _ge, crypto.SHA512, _bb)
	if err != nil {
		return "", err
	}
	_c := base64.StdEncoding.EncodeToString(_dbce)
	_c += "\n+\n"
	_c += base64.StdEncoding.EncodeToString(_gbg)
	return _c, nil
}

var defaultLicenseKey = MakeUnlicensedKey()

type LicenseKey struct {
	LicenseId    string     "json:\"license_id\""
	CustomerId   string     "json:\"customer_id\""
	CustomerName string     "json:\"customer_name\""
	Tier         string     "json:\"tier\""
	CreatedAt    time.Time  "json:\"-\""
	CreatedAtInt int64      "json:\"created_at\""
	ExpiresAt    *time.Time "json:\"-\""
	ExpiresAtInt int64      "json:\"expires_at\""
	CreatedBy    string     "json:\"created_by\""
	CreatorName  string     "json:\"creator_name\""
	CreatorEmail string     "json:\"creator_email\""
	UniPDF       bool       "json:\"unipdf\""
	UniOffice    bool       "json:\"unioffice\""
	UniHTML      bool       "json:\"unihtml\""
	Trial        bool       "json:\"trial\""
	_eg          bool
	_da          string
	_ged         bool
	_cdb         bool
}

func _ffd(_bgcd, _eef string) string {
	_fad := []byte(_bgcd)
	_ddcf := hmac.New(sha256.New, _fad)
	_ddcf.Write([]byte(_eef))
	return base64.StdEncoding.EncodeToString(_ddcf.Sum(nil))
}

func (lk *LicenseKey) getExpiryDateToCompare() time.Time {
	if lk.Trial {
		return time.Now().UTC()
	}
	return common.ReleasedAt
}

func newMeteredClient() *meteredClient {
	mc := meteredClient{url: "https://cloud.unidoc.io/api", client: &http.Client{Timeout: 30 * time.Second}}
	if url := os.Getenv("UNIDOC_LICENSE_SERVER_URL"); strings.HasPrefix(url, "http") {
		mc.url = url
	}
	return &mc
}

func getBody(header string, footer string, content string) (string, error) {
	_cg := strings.Index(content, header)
	if _cg == -1 {
		return "", fmt.Errorf("header not found")
	}
	_ded := strings.Index(content, footer)
	if _ded == -1 {
		return "", fmt.Errorf("footer not found")
	}
	_eb := _cg + len(header) + 1
	return content[_eb : _ded-1], nil
}

type MeteredStatus struct {
	OK      bool
	Credits int64
	Used    int64
}

type meteredUsageCheckinResp struct {
	Instance      string "json:\"inst\""
	Next          string "json:\"next\""
	Success       bool   "json:\"success\""
	Message       string "json:\"message\""
	RemainingDocs int    "json:\"rd\""
	LimitDocs     bool   "json:\"ld\""
}

type meteredStatusForm struct{}

const (
	LicenseTierUnlicensed = "unlicensed"
	LicenseTierCommunity  = "community"
	LicenseTierIndividual = "individual"
	LicenseTierBusiness   = "business"
)

type defaultStateHolder struct{}

func (_ege defaultStateHolder) updateState(_cce, _ddc, _eced string, _baa int, _efb bool, _fbc int, _dfe int, _dce time.Time, _gfe map[string]int, _egec ...interface{}) error {
	_egg, err := _cff()
	if err != nil {
		return err
	}
	if len(_cce) < 20 {
		return errors.New("invalid key")
	}
	_fcc := []byte(_cce)
	_adg := sha512.Sum512_256(_fcc[:20])
	_bca := hex.EncodeToString(_adg[:])
	_bbf := filepath.Join(_egg, _bca)
	var rs reportState
	rs.Docs = int64(_baa)
	rs.NumErrors = int64(_dfe)
	rs.LimitDocs = _efb
	rs.RemainingDocs = int64(_fbc)
	rs.LastWritten = time.Now().UTC()
	rs.LastReported = _dce
	rs.Instance = _ddc
	rs.Next = _eced
	rs.Usage = _gfe
	rs.UsageLogs = _egec
	_fccb, err := json.Marshal(rs)
	if err != nil {
		return err
	}
	const key = "ha9NK8]RbL*m4LKW"
	_fccb, err = encrypt([]byte(key), _fccb)
	if err != nil {
		return err
	}
	err = os.WriteFile(_bbf, _fccb, 0600)
	if err != nil {
		return err
	}
	return nil
}

var _aagc map[string]int

type meteredStatusResp struct {
	Valid        bool  "json:\"valid\""
	OrgCredits   int64 "json:\"org_credits\""
	OrgUsed      int64 "json:\"org_used\""
	OrgRemaining int64 "json:\"org_remaining\""
}

func _gfga(_dede *http.Response) (io.ReadCloser, error) {
	var _egd error
	var _ecdad io.ReadCloser
	switch strings.ToLower(_dede.Header.Get("Content-Encoding")) {
	case "gzip":
		_ecdad, _egd = gzip.NewReader(_dede.Body)
		if _egd != nil {
			return _ecdad, _egd
		}
		defer _ecdad.Close()
	default:
		_ecdad = _dede.Body
	}
	return _ecdad, nil
}

var _fbf []interface{}

var _eea = time.Date(2020, 1, 1, 0, 0, 0, 0, time.UTC)

func _dgc() ([]string, []string, error) {
	_cfcb, _aefa := net.Interfaces()
	if _aefa != nil {
		return nil, nil, _aefa
	}
	var _bcaa []string
	var _bcae []string
	for _, _abgb := range _cfcb {
		if _abgb.Flags&net.FlagUp == 0 || bytes.Equal(_abgb.HardwareAddr, nil) {
			continue
		}
		_gfd, _ffa := _abgb.Addrs()
		if _ffa != nil {
			return nil, nil, _ffa
		}
		_bcf := 0
		for _, _fed := range _gfd {
			var _afb net.IP
			switch _afac := _fed.(type) {
			case *net.IPNet:
				_afb = _afac.IP
			case *net.IPAddr:
				_afb = _afac.IP
			}
			if _afb.IsLoopback() {
				continue
			}
			if _afb.To4() == nil {
				continue
			}
			_bcae = append(_bcae, _afb.String())
			_bcf++
		}
		_gef := _abgb.HardwareAddr.String()
		if _gef != "" && _bcf > 0 {
			_bcaa = append(_bcaa, _gef)
		}
	}
	return _bcaa, _bcae, nil
}

func (lk *LicenseKey) Validate() error {
	if lk._eg {
		return nil
	}
	if len(lk.LicenseId) < 10 {
		return fmt.Errorf("invalid license: License Id")
	}
	if len(lk.CustomerId) < 10 {
		return fmt.Errorf("invalid license: Customer Id")
	}
	if len(lk.CustomerName) < 1 {
		return fmt.Errorf("invalid license: Customer Name")
	}
	if date20100101.After(lk.CreatedAt) {
		return fmt.Errorf("invalid license: Created At is invalid")
	}
	if lk.ExpiresAt == nil {
		_cgb := lk.CreatedAt.AddDate(1, 0, 0)
		if _eea.After(_cgb) {
			_cgb = _eea
		}
		lk.ExpiresAt = &_cgb
	}
	if lk.CreatedAt.After(*lk.ExpiresAt) {
		return fmt.Errorf("invalid license: Created At cannot be Greater than Expires At")
	}
	if lk.isExpired() {
		_fdb := "The license has already expired.\n" + "You may need to update the license key to the newest license key for your organization.\n" + "To find your newest license key, go to https://cloud.unidoc.io and go to the license menu."
		return fmt.Errorf("invalid license: %s", _fdb)
	}
	if len(lk.CreatorName) < 1 {
		return fmt.Errorf("invalid license: Creator name")
	}
	if len(lk.CreatorEmail) < 1 {
		return fmt.Errorf("invalid license: Creator email")
	}
	if lk.CreatedAt.After(date20190606) {
		if !lk.UniPDF {
			return fmt.Errorf("invalid license: This UniDoc key is invalid for UniPDF")
		}
	}
	return nil
}

func (mc *meteredClient) getStatus() (meteredStatusResp, error) {
	var msr meteredStatusResp
	_af := mc.url + "/metered/status"
	var msf meteredStatusForm
	_eeb, err := json.Marshal(msf)
	if err != nil {
		return msr, err
	}
	_def, err := _gdc(_eeb)
	if err != nil {
		return msr, err
	}
	req, err := http.NewRequest("POST", _af, _def)
	if err != nil {
		return msr, err
	}
	req.Header.Add("Content-Type", "application/json")
	req.Header.Add("Content-Encoding", "gzip")
	req.Header.Add("Accept-Encoding", "gzip")
	req.Header.Add("X-API-KEY", mc._gcg)
	resp, err := mc.client.Do(req)
	if err != nil {
		return msr, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		return msr, fmt.Errorf("failed to checkin, status code is: %d", resp.StatusCode)
	}
	_ccc, err := _gbd(resp)
	if err != nil {
		return msr, err
	}
	err = json.Unmarshal(_ccc, &msr)
	if err != nil {
		return msr, err
	}
	return msr, nil
}

func _ffg(_bdgd string, _efd string, _dfb string, _dbd bool) error {
	if defaultLicenseKey == nil {
		return errors.New("no license key")
	}
	if !defaultLicenseKey._eg || len(defaultLicenseKey._da) == 0 {
		return nil
	}
	if len(_bdgd) == 0 && !_dbd {
		return errors.New("docKey not set")
	}
	_edb.Lock()
	defer _edb.Unlock()
	if _gfc == nil {
		_gfc = map[string]struct{}{}
	}
	if _aagc == nil {
		_aagc = map[string]int{}
	}
	_cdg := 0
	if len(_bdgd) > 0 {
		_, _gee := _gfc[_bdgd]
		if !_gee {
			_gfc[_bdgd] = struct{}{}
			_cdg++
		}
		if defaultLicenseKey._cdb {
			_fbf = append(_fbf, map[string]interface{}{"time": time.Now().String(), "func": _efd, "ref": _bdgd[:8], "file": _dfb, "cost": _cdg})
			if _gee && _cdg == 0 {
				common.Log.Info("%s Ref: %s | %s | No credit used", time.Now().String(), _bdgd[:8], _efd)
			}
		}
	}
	if _cdg == 0 && !_dbd {
		return nil
	}
	_aagc[_efd]++
	_fdbe := time.Now()
	_acd, _afcf := _ceb.loadState(defaultLicenseKey._da)
	if _afcf != nil {
		common.Log.Debug("ERROR: %v", _afcf)
		return _afcf
	}
	_acd.UsageLogs = append(_acd.UsageLogs, _fbf...)
	if _acd.Usage == nil {
		_acd.Usage = map[string]int{}
	}
	for _ecda, _bdcf := range _aagc {
		if _ecda != "" {
			_acd.Usage[_ecda] += _bdcf
		}
	}
	_aagc = nil
	const _ccf = 24 * time.Hour
	const _fbe = 3 * 24 * time.Hour
	if len(_acd.Instance) == 0 || _fdbe.Sub(_acd.LastReported) > _ccf || (_acd.LimitDocs && _acd.RemainingDocs <= _acd.Docs+int64(_cdg)) || _dbd {
		_bdca, _bdbf := os.Hostname()
		if _bdbf != nil {
			return _bdbf
		}
		_aaac := _acd.Docs
		_eff, _cdgd, _bdbf := _dgc()
		if _bdbf != nil {
			common.Log.Debug("Unable to get local address: %s", _bdbf.Error())
			_eff = append(_eff, "information not available")
			_cdgd = append(_cdgd, "information not available")
		} else {
			sort.Strings(_cdgd)
			sort.Strings(_eff)
			_dgd, _ggc := getIP()
			if _ggc != nil {
				return _ggc
			}
			_ddb := false
			for _, _aeae := range _cdgd {
				if _aeae == _dgd.String() {
					_ddb = true
				}
			}
			if !_ddb {
				_cdgd = append(_cdgd, _dgd.String())
			}
		}
		_abg := newMeteredClient()
		_abg._gcg = defaultLicenseKey._da
		_aaac += int64(_cdg)
		_gfgb := meteredUsageCheckinForm{Instance: _acd.Instance, Next: _acd.Next, UsageNumber: int(_aaac), NumFailed: _acd.NumErrors, Hostname: _bdca, LocalIP: strings.Join(_cdgd, ", "), MacAddress: strings.Join(_eff, ", "), Package: "unipdf", PackageVersion: common.Version, Usage: _acd.Usage, IsPersistentCache: defaultLicenseKey._ged, Timestamp: _fdbe.Unix()}
		if len(_eff) == 0 {
			_gfgb.MacAddress = "none"
		}
		if defaultLicenseKey._cdb {
			_gfgb.UsageLogs = _acd.UsageLogs
		}
		_ade := int64(0)
		_bcgb := _acd.NumErrors
		_efbd := _fdbe
		_cca := 0
		_cec := _acd.LimitDocs
		_deag, _bdbf := _abg.checkinUsage(_gfgb)
		if _bdbf != nil {
			if _fdbe.Sub(_acd.LastReported) > _fbe {
				if !_deag.Success {
					return errors.New(_deag.Message)
				}
				return errors.New("too long since last successful checkin")
			}
			_ade = _aaac
			_bcgb++
			_efbd = _acd.LastReported
		} else {
			_cec = _deag.LimitDocs
			_cca = _deag.RemainingDocs
			_bcgb = 0
		}
		if len(_deag.Instance) == 0 {
			_deag.Instance = _gfgb.Instance
		}
		if len(_deag.Next) == 0 {
			_deag.Next = _gfgb.Next
		}
		_bdbf = _ceb.updateState(_abg._gcg, _deag.Instance, _deag.Next, int(_ade), _cec, _cca, int(_bcgb), _efbd, nil)
		if _bdbf != nil {
			return _bdbf
		}
		if !_deag.Success {
			return fmt.Errorf("error: %s", _deag.Message)
		}
	} else {
		_afcf = _ceb.updateState(defaultLicenseKey._da, _acd.Instance, _acd.Next, int(_acd.Docs)+_cdg, _acd.LimitDocs, int(_acd.RemainingDocs), int(_acd.NumErrors), _acd.LastReported, _acd.Usage, _acd.UsageLogs...)
		if _afcf != nil {
			return _afcf
		}
	}
	if defaultLicenseKey._cdb && len(_bdgd) > 0 {
		_fdda := ""
		if _dfb != "" {
			_fdda = fmt.Sprintf("File %s |", _dfb)
		}
		common.Log.Info("%s | %s Ref: %s | %s | %d credit(s) used", _fdbe.String(), _fdda, _bdgd[:8], _efd, _cdg)
	}
	return nil
}

var _ceb stateLoader = defaultStateHolder{}

func (mc *meteredClient) checkinUsage(_gfg meteredUsageCheckinForm) (meteredUsageCheckinResp, error) {
	_gfg.Package = "unipdf"
	_gfg.PackageVersion = common.Version
	var _fa meteredUsageCheckinResp
	_afa := mc.url + "/metered/usage_checkin"
	_ffb, _ebe := json.Marshal(_gfg)
	if _ebe != nil {
		return _fa, _ebe
	}
	_bad, _ebe := _gdc(_ffb)
	if _ebe != nil {
		return _fa, _ebe
	}
	_aec, _ebe := http.NewRequest("POST", _afa, _bad)
	if _ebe != nil {
		return _fa, _ebe
	}
	_aec.Header.Add("Content-Type", "application/json")
	_aec.Header.Add("Content-Encoding", "gzip")
	_aec.Header.Add("Accept-Encoding", "gzip")
	_aec.Header.Add("X-API-KEY", mc._gcg)
	_fb, _ebe := mc.client.Do(_aec)
	if _ebe != nil {
		return _fa, _ebe
	}
	defer _fb.Body.Close()
	if _fb.StatusCode != 200 {
		_ece, _aca := _gbd(_fb)
		if _aca != nil {
			return _fa, _aca
		}
		_aca = json.Unmarshal(_ece, &_fa)
		if _aca != nil {
			return _fa, _aca
		}
		return _fa, fmt.Errorf("failed to checkin, status code is: %d", _fb.StatusCode)
	}
	_fgd := _fb.Header.Get("X-UC-Signature")
	_dac := _ffd(_gfg.MacAddress, string(_ffb))
	if _dac != _fgd {
		common.Log.Error("Invalid response signature, set the license server to https://cloud.unidoc.io/api")
		return _fa, errors.New("failed to checkin, invalid server response")
	}
	_ace, _ebe := _gbd(_fb)
	if _ebe != nil {
		return _fa, _ebe
	}
	_ebe = json.Unmarshal(_ace, &_fa)
	if _ebe != nil {
		return _fa, _ebe
	}
	return _fa, nil
}

var date20190606 = time.Date(2019, 6, 6, 0, 0, 0, 0, time.UTC)

func (_aaa defaultStateHolder) loadState(_aadb string) (reportState, error) {
	_bbb, _caf := _cff()
	if _caf != nil {
		return reportState{}, _caf
	}
	_caf = os.MkdirAll(_bbb, 0777)
	if _caf != nil {
		return reportState{}, _caf
	}
	if len(_aadb) < 20 {
		return reportState{}, errors.New("invalid key")
	}
	_fbcg := []byte(_aadb)
	_daf := sha512.Sum512_256(_fbcg[:20])
	_gag := hex.EncodeToString(_daf[:])
	_ecd := filepath.Join(_bbb, _gag)
	_ecf, _caf := os.ReadFile(_ecd)
	if _caf != nil {
		if os.IsNotExist(_caf) {
			return reportState{}, nil
		}
		common.Log.Debug("ERROR: %v", _caf)
		return reportState{}, errors.New("invalid data")
	}
	const _ecef = "ha9NK8]RbL*m4LKW"
	_ecf, _caf = _fda([]byte(_ecef), _ecf)
	if _caf != nil {
		return reportState{}, _caf
	}
	var _bdc reportState
	_caf = json.Unmarshal(_ecf, &_bdc)
	if _caf != nil {
		common.Log.Debug("ERROR: Invalid data: %v", _caf)
		return reportState{}, errors.New("invalid data")
	}
	return _bdc, nil
}

type meteredClient struct {
	url    string
	_gcg   string
	client *http.Client
}

func getIP() (net.IP, error) {
	conn, err := net.Dial("udp", "8.8.8.8:80")
	if err != nil {
		return nil, err
	}
	defer conn.Close()
	udpaddr := conn.LocalAddr().(*net.UDPAddr)
	return udpaddr.IP, nil
}

func SetMeteredKey(apiKey string) error {
	if len(apiKey) == 0 {
		common.Log.Error("Metered License API Key must not be empty")
		common.Log.Error("- Grab one in the Free Tier at https://cloud.unidoc.io")
		return fmt.Errorf("metered license api key must not be empty: create one at https://cloud.unidoc.io")
	}
	if defaultLicenseKey != nil && (defaultLicenseKey._eg || defaultLicenseKey.Tier != LicenseTierUnlicensed) {
		common.Log.Error("ERROR: Cannot set license key twice - Should just initialize once")
		return errors.New("license key already set")
	}
	_fdbd := newMeteredClient()
	_fdbd._gcg = apiKey
	_aac, _aee := _fdbd.getStatus()
	if _aee != nil {
		return _aee
	}
	if !_aac.Valid {
		return errors.New("key not valid")
	}
	_eeeg := &LicenseKey{_eg: true, _da: apiKey, _ged: true}
	defaultLicenseKey = _eeeg
	return nil
}

const UnipdfCustomerName = "UNIPDF_CUSTOMER_NAME"

var _gfc map[string]struct{}

func Track(docKey string, useKey string, docName string) error {
	return _ffg(docKey, useKey, docName, !defaultLicenseKey._ged)
}

func decrypt(pubkey string, cipher string) ([]byte, error) {
	var (
		_ag  int
		_gbe string
	)
	for _, _gbe = range []string{"\n+\n", "\r\n+\r\n", " + "} {
		if _ag = strings.Index(cipher, _gbe); _ag != -1 {
			break
		}
	}
	if _ag == -1 {
		return nil, fmt.Errorf("invalid input, signature separator")
	}
	_fdcc := cipher[:_ag]
	_aad := _ag + len(_gbe)
	_eaa := cipher[_aad:]
	if _fdcc == "" || _eaa == "" {
		return nil, fmt.Errorf("invalid input, missing original or signature")
	}
	_bed, _gc := base64.StdEncoding.DecodeString(_fdcc)
	if _gc != nil {
		return nil, fmt.Errorf("invalid input original")
	}
	_bdb, _gc := base64.StdEncoding.DecodeString(_eaa)
	if _gc != nil {
		return nil, fmt.Errorf("invalid input signature")
	}
	_ed, _ := pem.Decode([]byte(pubkey))
	if _ed == nil {
		return nil, fmt.Errorf("PubKey failed")
	}
	_dd, _gc := x509.ParsePKIXPublicKey(_ed.Bytes)
	if _gc != nil {
		return nil, _gc
	}
	_bgc := _dd.(*rsa.PublicKey)
	if _bgc == nil {
		return nil, fmt.Errorf("PubKey conversion failed")
	}
	_ggd := sha512.New()
	_ggd.Write(_bed)
	_eaf := _ggd.Sum(nil)
	_gc = rsa.VerifyPKCS1v15(_bgc, crypto.SHA512, _eaf, _bdb)
	if _gc != nil {
		return nil, _gc
	}
	return _bed, nil
}

func SetMeteredKeyUsageLogVerboseMode(val bool) { defaultLicenseKey._cdb = val }

const pubKey = "\n-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmFUiyd7b5XjpkP5Rap4w\nDc1dyzIQ4LekxrvytnEMpNUbo6iA74V8ruZOvrScsf2QeN9/qrUG8qEbUWdoEYq+\notFNAFNxlGbxbDHcdGVaM0OXdXgDyL5aIEagL0c5pwjIdPGIn46f78eMJ+JkdcpD\nDJaqYXdrz5KeshjSiIaa7menBIAXS4UFxNfHhN0HCYZYqQG7bK+s5rRHonydNWEG\nH8Myvr2pya2KrMumfmAxUB6fenC/4O0Wr8gfPOU8RitmbDvQPIRXOL4vTBrBdbaA\n9nwNP+i//20MT2bxmeWB+gpcEhGpXZ733azQxrC3J4v3CZmENStDK/KDSPKUGfu6\nfwIDAQAB\n-----END PUBLIC KEY-----\n"

func (lk *LicenseKey) IsLicensed() bool { return lk.Tier != LicenseTierUnlicensed || lk._eg }

func (lk *LicenseKey) TypeToString() string {
	if lk._eg {
		return "Metered subscription"
	}
	if lk.Tier == LicenseTierUnlicensed {
		return "Unlicensed"
	}
	if lk.Tier == LicenseTierCommunity {
		return "AGPLv3 Open Source Community License"
	}
	if lk.Tier == LicenseTierIndividual || lk.Tier == "indie" {
		return "Commercial License - Individual"
	}
	return "Commercial License - Business"
}

func (lk *LicenseKey) isExpired() bool {
	return lk.getExpiryDateToCompare().After(*lk.ExpiresAt)
}

func getLicenseKey(content string) (LicenseKey, error) {
	var licenseKey LicenseKey
	body, err := getBody(licenseKeyHeader, licenseKeyFooter, content)
	if err != nil {
		return licenseKey, err
	}
	decrypted, err := decrypt(pubKey, body)
	if err != nil {
		return licenseKey, err
	}
	err = json.Unmarshal(decrypted, &licenseKey)
	if err != nil {
		return licenseKey, err
	}
	licenseKey.CreatedAt = time.Unix(licenseKey.CreatedAtInt, 0)
	if licenseKey.ExpiresAtInt > 0 {
		_bbd := time.Unix(licenseKey.ExpiresAtInt, 0)
		licenseKey.ExpiresAt = &_bbd
	}
	return licenseKey, nil
}

func SetLicenseKey(content string, customerName string) error {
	licenseKey, err := getLicenseKey(content)
	if err != nil {
		common.Log.Error("License code decode error: %v", err)
		return err
	}
	if !strings.EqualFold(licenseKey.CustomerName, customerName) {
		common.Log.Error("License code issue - Customer name mismatch, expected '%s', but got '%s'", licenseKey.CustomerName, customerName)
		return fmt.Errorf("customer name mismatch, expected '%s', but got '%s'", licenseKey.CustomerName, customerName)
	}
	err = licenseKey.Validate()
	if err != nil {
		common.Log.Error("License code validation error: %v", err)
		return err
	}
	defaultLicenseKey = &licenseKey
	return nil
}

type meteredUsageCheckinForm struct {
	Instance          string         "json:\"inst\""
	Next              string         "json:\"next\""
	UsageNumber       int            "json:\"usage_number\""
	NumFailed         int64          "json:\"num_failed\""
	Hostname          string         "json:\"hostname\""
	LocalIP           string         "json:\"local_ip\""
	MacAddress        string         "json:\"mac_address\""
	Package           string         "json:\"package\""
	PackageVersion    string         "json:\"package_version\""
	Usage             map[string]int "json:\"u\""
	IsPersistentCache bool           "json:\"is_persistent_cache\""
	Timestamp         int64          "json:\"timestamp\""
	UsageLogs         []interface{}  "json:\"ul,omitempty\""
}

func MakeUnlicensedKey() *LicenseKey {
	_eaaf := LicenseKey{}
	_eaaf.CustomerName = "Unlicensed"
	_eaaf.Tier = LicenseTierUnlicensed
	_eaaf.CreatedAt = time.Now().UTC()
	_eaaf.CreatedAtInt = _eaaf.CreatedAt.Unix()
	return &_eaaf
}

const UnipdfLicensePath = "UNIPDF_LICENSE_PATH"

const UnidocLicenseDir = "UNIDOC_LICENSE_DIR"

func _gdc(_ega []byte) (io.Reader, error) {
	_cdab := new(bytes.Buffer)
	_gba := gzip.NewWriter(_cdab)
	_gba.Write(_ega)
	_gcd := _gba.Close()
	if _gcd != nil {
		return nil, _gcd
	}
	return _cdab, nil
}

type stateLoader interface {
	loadState(_dcc string) (reportState, error)
	updateState(_dg, _fcf, _cfc string, _gbf int, _beg bool, _eceg int, _dee int, _efg time.Time, _cda map[string]int, _bde ...interface{}) error
}

func init() {
	_faf := os.Getenv(UnipdfLicensePath)
	_ggb := os.Getenv(UnipdfCustomerName)
	if len(_faf) == 0 || len(_ggb) == 0 {
		return
	}
	_efbf, _gbeba := os.ReadFile(_faf)
	if _gbeba != nil {
		common.Log.Error("Unable to read license code file: %v", _gbeba)
		return
	}
	_gbeba = SetLicenseKey(string(_efbf), _ggb)
	if _gbeba != nil {
		common.Log.Error("Unable to load license code: %v", _gbeba)
		return
	}
}

func (lk *LicenseKey) ToString() string {
	if lk._eg {
		return "Metered subscription"
	}
	_fc := fmt.Sprintf("License Id: %s\n", lk.LicenseId)
	_fc += fmt.Sprintf("Customer Id: %s\n", lk.CustomerId)
	_fc += fmt.Sprintf("Customer Name: %s\n", lk.CustomerName)
	_fc += fmt.Sprintf("Tier: %s\n", lk.Tier)
	_fc += fmt.Sprintf("Created At: %s\n", common.UtcTimeFormat(lk.CreatedAt))
	if lk.ExpiresAt == nil {
		_fc += "Expires At: Never\n"
	} else {
		_fc += fmt.Sprintf("Expires At: %s\n", common.UtcTimeFormat(*lk.ExpiresAt))
	}
	_fc += fmt.Sprintf("Creator: %s <%s>\n", lk.CreatorName, lk.CreatorEmail)
	return _fc
}

func encrypt(key, _edd []byte) ([]byte, error) {
	_gcgd, _cef := aes.NewCipher(key)
	if _cef != nil {
		return nil, _cef
	}
	_fag := make([]byte, aes.BlockSize+len(_edd))
	_cag := _fag[:aes.BlockSize]
	if _, _fdf := io.ReadFull(rand.Reader, _cag); _fdf != nil {
		return nil, _fdf
	}
	_cfd := cipher.NewCFBEncrypter(_gcgd, _cag)
	_cfd.XORKeyStream(_fag[aes.BlockSize:], _edd)
	_efc := make([]byte, base64.URLEncoding.EncodedLen(len(_fag)))
	base64.URLEncoding.Encode(_efc, _fag)
	return _efc, nil
}

func SetMeteredKeyPersistentCache(val bool) { defaultLicenseKey._ged = val }

func GetLicenseKey() *LicenseKey {
	if defaultLicenseKey == nil {
		return nil
	}
	_cgd := *defaultLicenseKey
	return &_cgd
}

func _aefc() string {
	_aefb := os.Getenv("HOME")
	if len(_aefb) == 0 {
		_aefb, _ = os.UserHomeDir()
	}
	return _aefb
}

func _gbd(_aba *http.Response) ([]byte, error) {
	var _acad []byte
	_cga, _cbf := _gfga(_aba)
	if _cbf != nil {
		return _acad, _cbf
	}
	return io.ReadAll(_cga)
}

func GetMeteredState() (MeteredStatus, error) {
	if defaultLicenseKey == nil {
		return MeteredStatus{}, errors.New("license key not set")
	}
	if !defaultLicenseKey._eg || len(defaultLicenseKey._da) == 0 {
		return MeteredStatus{}, errors.New("api key not set")
	}
	_ebec, _cccb := _ceb.loadState(defaultLicenseKey._da)
	if _cccb != nil {
		common.Log.Debug("ERROR: %v", _cccb)
		return MeteredStatus{}, _cccb
	}
	if _ebec.Docs > 0 {
		_bda := _ffg("", "", "", true)
		if _bda != nil {
			return MeteredStatus{}, _bda
		}
	}
	_edb.Lock()
	defer _edb.Unlock()
	_fae := newMeteredClient()
	_fae._gcg = defaultLicenseKey._da
	_agdc, _cccb := _fae.getStatus()
	if _cccb != nil {
		return MeteredStatus{}, _cccb
	}
	if !_agdc.Valid {
		return MeteredStatus{}, errors.New("key not valid")
	}
	_aaea := MeteredStatus{OK: true, Credits: _agdc.OrgCredits, Used: _agdc.OrgUsed}
	return _aaea, nil
}

type reportState struct {
	Instance      string         "json:\"inst\""
	Next          string         "json:\"n\""
	Docs          int64          "json:\"d\""
	NumErrors     int64          "json:\"e\""
	LimitDocs     bool           "json:\"ld\""
	RemainingDocs int64          "json:\"rd\""
	LastReported  time.Time      "json:\"lr\""
	LastWritten   time.Time      "json:\"lw\""
	Usage         map[string]int "json:\"u\""
	UsageLogs     []interface{}  "json:\"ul,omitempty\""
}

func _fda(_cagd, _eec []byte) ([]byte, error) {
	_geec := make([]byte, base64.URLEncoding.DecodedLen(len(_eec)))
	_daeb, _dace := base64.URLEncoding.Decode(_geec, _eec)
	if _dace != nil {
		return nil, _dace
	}
	_geec = _geec[:_daeb]
	_cae, _dace := aes.NewCipher(_cagd)
	if _dace != nil {
		return nil, _dace
	}
	if len(_geec) < aes.BlockSize {
		return nil, errors.New("ciphertext too short")
	}
	_fdbdd := _geec[:aes.BlockSize]
	_geec = _geec[aes.BlockSize:]
	_adeb := cipher.NewCFBDecrypter(_cae, _fdbdd)
	_adeb.XORKeyStream(_geec, _geec)
	return _geec, nil
}
